version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip install flake8
          name: Install dependencies
      - python/save-cache
      - run:
          command: flake8 --ignore=E501
          name: Lint

workflows:
  main:
    jobs:
      - build-and-test
